LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator Class Reference
org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator Class Reference abstract
environment agent generator
Public Member Functions
IBaseEnvironmentGenerator (final InputStream p_stream, final Stream< IAction > p_actions, final Class<? extends IEnvironment > p_environmentclass) throws Exception
final IEnvironment generatesingle (final Object... p_data)
Protected Member Functions
abstract IEnvironment generate (final IAgentConfiguration< IEnvironment > p_configuration, final int p_rows, final int p_columns, final double p_cellsize, final IRouting p_routing)
generate
Detailed Description
Bug:
fix docu
Definition at line 43 of file IBaseEnvironmentGenerator.java.
Constructor & Destructor Documentation
IBaseEnvironmentGenerator()
org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.IBaseEnvironmentGenerator (final InputStream p_stream, final Stream< IAction > p_actions, final Class<? extends IEnvironment > p_environmentclass) throws Exception
Definition at line 45 of file IBaseEnvironmentGenerator.java.
Member Function Documentation
generate()
abstract IEnvironment org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.generate (final IAgentConfiguration< IEnvironment > p_configuration, final int p_rows, final int p_columns, final double p_cellsize, final IRouting p_routing) abstract protected
Parameters
p_configuration configuration
p_rows rows
p_columns columns
p_cellsize cellsize
p_routing routing
Returns
IEnvironment
Referenced by org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.generatesingle().
generatesingle()
final IEnvironment org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.generatesingle (final Object... p_data)
Definition at line 53 of file IBaseEnvironmentGenerator.java.
References org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.generate(), and org.lightjason.trafficsimulation.ui.CHTTPServer.register().