LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite Class Reference
org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite Class Reference
pedestrian sprite
Inherits IBaseSprite< CPedestrian >.
Public Member Functions
final ISprite< CPedestrian > call () throws Exception
final synchronized ISprite< CPedestrian > spriteinitialize (final int p_rows, final int p_columns, final int p_cellsize, final float p_unit)
Private Member Functions
CPedestrianSprite (final CPedestrian p_wrapping)
ctor
Static Private Member Functions
static void spriteposition (final Sprite p_sprite, final DoubleMatrix1D p_position)
sets the position of the sprite
static Texture texture (final int p_cellsize)
creates the texture
Static Private Attributes
static final AtomicReference< Texture > TEXTURE = new AtomicReference<>()
Detailed Description
Definition at line 120 of file TestCViewPedstrian.java.
Constructor & Destructor Documentation
CPedestrianSprite()
org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.CPedestrianSprite (final CPedestrian p_wrapping) private
Parameters
p_wrapping wrapping object
Definition at line 132 of file TestCViewPedstrian.java.
Member Function Documentation
call()
final ISprite<CPedestrian> org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.call () throws Exception
Definition at line 138 of file TestCViewPedstrian.java.
References org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteposition().
spriteinitialize()
final synchronized ISprite<CPedestrian> org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteinitialize (final int p_rows, final int p_columns, final int p_cellsize, final float p_unit)
Definition at line 163 of file TestCViewPedstrian.java.
References org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteposition(), and org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.texture().
spriteposition()
static void org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteposition (final Sprite p_sprite, final DoubleMatrix1D p_position) static private
Parameters
p_sprite sprite
p_position position
Definition at line 183 of file TestCViewPedstrian.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.call(), and org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteinitialize().
texture()
static Texture org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.texture (final int p_cellsize) static private
Returns
texture initialize
Definition at line 150 of file TestCViewPedstrian.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.spriteinitialize().
Member Data Documentation
TEXTURE
final AtomicReference<Texture> org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.CPedestrianSprite.TEXTURE = new AtomicReference<>() static private
Definition at line 125 of file TestCViewPedstrian.java.