LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?> Interface Template Reference
org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?> Interface Template Reference
object interface
Classes
interface IGenerator
generator interface
Public Member Functions
Stream< ILiteral > literal (final IObject<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
get literal of the object
String name ()
name of the object
DoubleMatrix1D position ()
position of the object
Detailed Description
Definition at line 37 of file IObject.java.
Member Function Documentation
literal() [1/2]
Stream<ILiteral> org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.literal (final IObject<?>... p_object)
Parameters
p_object objects
Returns
stream of literal
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
Referenced by org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.CEnvironmentBeliefbase.streamLiteral().
literal() [2/2]
Stream<ILiteral> org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.literal (final Stream< IObject<?>> p_object)
Parameters
p_object objects
Returns
stream of literal
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
name()
String org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.name ()
Returns
string name
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
Referenced by org.lightjason.trafficsimulation.actions.CSend.execute(), and org.lightjason.trafficsimulation.actions.CBroadcast.execute().
position()
DoubleMatrix1D org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.position ()
Returns
position
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.