LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.EObjectFactory Enum Reference
org.lightjason.trafficsimulation.simulation.EObjectFactory Enum Reference
class for generating object-generators
Public Member Functions
final IAgentGenerator<? extends IObject<?> > generate (final InputStream p_stream, final Stream< IAction > p_actions, final IEnvironment p_environment) throws Exception
generates a agent generator
final IAgentGenerator<? extends IObject<?> > generate (final InputStream p_stream, final Stream< IAction > p_actions) throws Exception
generator
Static Public Member Functions
static void resetcount ()
resets all generator counters
Public Attributes
AREA
ENVIRONMENT
PEDESTRIAN
VEHICLE
VEHICLE_TRAFFICLIGHT
Detailed Description
Todo:
fix documentation
Definition at line 46 of file EObjectFactory.java.
Member Function Documentation
generate() [1/2]
final IAgentGenerator<? extends IObject<?> > org.lightjason.trafficsimulation.simulation.EObjectFactory.generate (final InputStream p_stream, final Stream< IAction > p_actions, final IEnvironment p_environment) throws Exception
Parameters
p_stream asl input stream
p_actions action list
p_environment environment reference
Returns
agent generator
Exceptions
Exception on any error
Definition at line 70 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.IBaseTest.generate(), and org.lightjason.trafficsimulation.IBaseTest.generatemultiple().
generate() [2/2]
final IAgentGenerator<? extends IObject<?> > org.lightjason.trafficsimulation.simulation.EObjectFactory.generate (final InputStream p_stream, final Stream< IAction > p_actions) throws Exception
Parameters
p_stream steam
p_actions actions
Returns
agent generator
Exceptions
Exception on any error
Definition at line 106 of file EObjectFactory.java.
resetcount()
static void org.lightjason.trafficsimulation.simulation.EObjectFactory.resetcount () static
Definition at line 115 of file EObjectFactory.java.
References org.lightjason.trafficsimulation.simulation.stationary.trafficlight.CTrafficLightPedestrian.CGenerator.resetcount(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.CTrafficLightVehicle.CGenerator.resetcount(), org.lightjason.trafficsimulation.simulation.movable.CPedestrian.CGenerator.resetcount(), and org.lightjason.trafficsimulation.simulation.movable.CVehicle.CGenerator.resetcount().
Member Data Documentation
AREA
org.lightjason.trafficsimulation.simulation.EObjectFactory.AREA
Definition at line 50 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.addarea().
ENVIRONMENT
org.lightjason.trafficsimulation.simulation.EObjectFactory.ENVIRONMENT
Definition at line 48 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.IBaseTest.initializeenvironment(), and org.lightjason.trafficsimulation.CMain.main().
PEDESTRIAN
org.lightjason.trafficsimulation.simulation.EObjectFactory.PEDESTRIAN
Definition at line 55 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.initialize(), and org.lightjason.trafficsimulation.CMain.main().
VEHICLE
org.lightjason.trafficsimulation.simulation.EObjectFactory.VEHICLE
Definition at line 52 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.initialize().
VEHICLE_TRAFFICLIGHT
org.lightjason.trafficsimulation.simulation.EObjectFactory.VEHICLE_TRAFFICLIGHT
Definition at line 53 of file EObjectFactory.java.
Referenced by org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.initialize().