LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.environment.CEnvironment Class Reference
org.lightjason.trafficsimulation.simulation.environment.CEnvironment Class Reference
environment class
Classes
class CGenerator
generator of the environment
Public Member Functions
final synchronized boolean empty (final DoubleMatrix1D p_position)
checks if a position is empty
final synchronized IObject<?> get (final DoubleMatrix1D p_position)
returns an object from the given position
final Stream< ILiteral > literal (final IObject<?>... p_object)
get literal of the object
final Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
get literal of the object
final synchronized IMoveable<?> move (final IMoveable<?> p_moveable, final DoubleMatrix1D p_newposition)
move a moveable
final String name ()
name of the object
final DoubleMatrix1D position ()
position of the object
final synchronized IObject<?> remove (final IObject<?> p_object)
remove object
final List< DoubleMatrix1D > route (final DoubleMatrix1D p_start, final DoubleMatrix1D p_end)
calculate route
final double routestimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
calculate estimated time of a route
Private Member Functions
CEnvironment (final IAgentConfiguration< IEnvironment > p_configuration, final int p_column, final int p_row, final double p_size, final IRouting p_routing)
ctor
void addarea (final String p_file, final Object... p_data)
add an area to the environment
void removearea ()
removes an area
Private Attributes
final Map< String, CArea > m_areas
map of the areas
final ObjectMatrix2D m_objectgrid
matrix with agents positions
final IRouting m_routing
routing algorithm
Static Private Attributes
static final String FUNCTOR = "environment"
literal name
static final long serialVersionUID = -993173756668246918L
serial id
Detailed Description
Definition at line 58 of file CEnvironment.java.
Constructor & Destructor Documentation
CEnvironment()
org.lightjason.trafficsimulation.simulation.environment.CEnvironment.CEnvironment (final IAgentConfiguration< IEnvironment > p_configuration, final int p_column, final int p_row, final double p_size, final IRouting p_routing) private
Parameters
p_configuration agent configuration
p_column number of column cells
p_row number of row cells
p_size cell size
Bug:
fix cell size to floating-point
Definition at line 91 of file CEnvironment.java.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.CGenerator.generate().
Member Function Documentation
addarea()
void org.lightjason.trafficsimulation.simulation.environment.CEnvironment.addarea (final String p_file, final Object... p_data) private
Parameters
p_file asl file
p_data data
Exceptions
Exception any error
Todo:
generator must be refactor for better file access
modify exception handling with agent plan failure
create better action naming schema
Definition at line 206 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.EObjectFactory.AREA, org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.name(), and org.lightjason.trafficsimulation.simulation.environment.CEnvironment.name().
empty()
final synchronized boolean org.lightjason.trafficsimulation.simulation.environment.CEnvironment.empty (final DoubleMatrix1D p_position)
Parameters
p_position position
Returns
boolean result
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 156 of file CEnvironment.java.
get()
final synchronized IObject<?> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.get (final DoubleMatrix1D p_position)
Parameters
p_position position vector
Returns
object or null
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 163 of file CEnvironment.java.
literal() [1/2]
final Stream<ILiteral> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.literal (final IObject<?>... p_object)
Parameters
p_object objects
Returns
stream of literal
Implements org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.
Definition at line 171 of file CEnvironment.java.
literal() [2/2]
final Stream<ILiteral> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.literal (final Stream< IObject<?>> p_object)
Parameters
p_object objects
Returns
stream of literal
Implements org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.
Definition at line 177 of file CEnvironment.java.
move()
final synchronized IMoveable<?> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.move (final IMoveable<?> p_moveable, final DoubleMatrix1D p_newposition)
Parameters
p_moveable object, which should be moved (must store the current position)
p_newposition new position
Returns
object reference
Bug:
check parameter and generics
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 128 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.movable.IMoveable< T extends IMoveable<?>.move(), and org.lightjason.trafficsimulation.simulation.movable.IMoveable< T extends IMoveable<?>.moveable().
name()
final String org.lightjason.trafficsimulation.simulation.environment.CEnvironment.name ()
Returns
string name
Implements org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.
Definition at line 183 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.environment.CEnvironment.FUNCTOR.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.addarea(), and org.lightjason.trafficsimulation.simulation.environment.CEnvironment.position().
position()
final DoubleMatrix1D org.lightjason.trafficsimulation.simulation.environment.CEnvironment.position ()
Returns
position
Implements org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>.
Definition at line 189 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.environment.CEnvironment.name().
remove()
final synchronized IObject<?> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.remove (final IObject<?> p_object)
Parameters
p_object element
Returns
Bug:
check parameter
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 147 of file CEnvironment.java.
removearea()
void org.lightjason.trafficsimulation.simulation.environment.CEnvironment.removearea () private
Todo:
must be implemented
Definition at line 235 of file CEnvironment.java.
route()
final List<DoubleMatrix1D> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.route (final DoubleMatrix1D p_start, final DoubleMatrix1D p_end)
Parameters
p_start start position
p_end target position
Returns
list of tuples of the cellindex
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 107 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.IRouting.route().
routestimatedtime()
final double org.lightjason.trafficsimulation.simulation.environment.CEnvironment.routestimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
Parameters
p_route current route
p_speed current speed
Returns
estimated time
Implements org.lightjason.trafficsimulation.simulation.environment.IEnvironment.
Definition at line 113 of file CEnvironment.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.IRouting.estimatedtime().
Member Data Documentation
FUNCTOR
final String org.lightjason.trafficsimulation.simulation.environment.CEnvironment.FUNCTOR = "environment" static private
Definition at line 67 of file CEnvironment.java.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.name().
m_areas
final Map<String, CArea> org.lightjason.trafficsimulation.simulation.environment.CEnvironment.m_areas private
Definition at line 79 of file CEnvironment.java.
m_objectgrid
final ObjectMatrix2D org.lightjason.trafficsimulation.simulation.environment.CEnvironment.m_objectgrid private
Definition at line 75 of file CEnvironment.java.
m_routing
final IRouting org.lightjason.trafficsimulation.simulation.environment.CEnvironment.m_routing private
Definition at line 71 of file CEnvironment.java.
serialVersionUID
final long org.lightjason.trafficsimulation.simulation.environment.CEnvironment.serialVersionUID = -993173756668246918L static private
Definition at line 63 of file CEnvironment.java.