LightJason - TrafficSimulation: org.lightjason.trafficsimulation.ui.CHTTPServer Class Reference
org.lightjason.trafficsimulation.ui.CHTTPServer Class Reference
Jersey-Jetty-HTTP server for UI.
Static Public Member Functions
static void execute ()
execute the server instance
static void initialize ()
run initialize without start-up of the server
static< T extends IObject<?> T register (final T p_agent, final String... p_group)
register agent if server is started
static< T extends IObject<?> T register (final Pair< T, Stream< String >> p_agentgroup)
register agent if server started
Private Member Functions
CHTTPServer ()
ctor
Private Attributes
final CApplication m_restagent = new CApplication()
REST-API application.
final Server m_server
server instance
Static Private Attributes
static final CHTTPServer INSTANCE = CConfiguration.INSTANCE.<Boolean>getOrDefault(false, "httpserver", "enable") ? new CHTTPServer() : null
webservcer instance
Detailed Description
debug: -Dorg.eclipse.jetty.servlet.LEVEL=ALL
Definition at line 54 of file CHTTPServer.java.
Constructor & Destructor Documentation
CHTTPServer()
org.lightjason.trafficsimulation.ui.CHTTPServer.CHTTPServer () private
Definition at line 72 of file CHTTPServer.java.
References org.lightjason.trafficsimulation.CConfiguration.INSTANCE, and org.lightjason.trafficsimulation.CCommon.PACKAGEPATH.
Member Function Documentation
execute()
static void org.lightjason.trafficsimulation.ui.CHTTPServer.execute () static
Definition at line 104 of file CHTTPServer.java.
References org.lightjason.trafficsimulation.CConfiguration.INSTANCE, and org.lightjason.trafficsimulation.ui.CHTTPServer.m_server.
Referenced by org.lightjason.trafficsimulation.CMain.main().
initialize()
static void org.lightjason.trafficsimulation.ui.CHTTPServer.initialize () static
Definition at line 97 of file CHTTPServer.java.
Referenced by org.lightjason.trafficsimulation.CMain.main().
register() [1/2]
static <T extends IObject<?> T org.lightjason.trafficsimulation.ui.CHTTPServer.register (final T p_agent, final String... p_group) static
Parameters
p_agent agent object
p_group additional group
Returns
agent object
Definition at line 141 of file CHTTPServer.java.
References org.lightjason.trafficsimulation.ui.CHTTPServer.m_restagent.
Referenced by org.lightjason.trafficsimulation.simulation.environment.IBaseEnvironmentGenerator.generatesingle(), and org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.IBaseGenerator< T extends IObject<?>.generatesingle().
register() [2/2]
static <T extends IObject<?> T org.lightjason.trafficsimulation.ui.CHTTPServer.register (final Pair< T, Stream< String >> p_agentgroup) static
Parameters
p_agentgroup tupel of agent and stream of group names
Template Parameters
T agent type
Returns
agent object
Definition at line 158 of file CHTTPServer.java.
Member Data Documentation
INSTANCE
final CHTTPServer org.lightjason.trafficsimulation.ui.CHTTPServer.INSTANCE = CConfiguration.INSTANCE.<Boolean>getOrDefault(false, "httpserver", "enable") ? new CHTTPServer() : null static private
Definition at line 59 of file CHTTPServer.java.
m_restagent
final CApplication org.lightjason.trafficsimulation.ui.CHTTPServer.m_restagent = new CApplication() private
Definition at line 67 of file CHTTPServer.java.
Referenced by org.lightjason.trafficsimulation.ui.CHTTPServer.register().
m_server
final Server org.lightjason.trafficsimulation.ui.CHTTPServer.m_server private
Definition at line 63 of file CHTTPServer.java.
Referenced by org.lightjason.trafficsimulation.ui.CHTTPServer.execute().