LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus Class Reference
org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus Class Reference
JPS+ algorithm.
Classes
class CCompareJumpPoint
class to compare two jump-points
class CJumpPoint
jump-point with a static class "static" means that the class can exists without the CJPSPlus object "final" no inheritance can be create
Public Member Functions
final double estimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
calculated the estimated time to move the path
final IRouting initialize (final ObjectMatrix2D p_objects)
runs the initialization process from the environment
final List< DoubleMatrix1D > route (final ObjectMatrix2D p_objects, final DoubleMatrix1D p_currentposition, final DoubleMatrix1D p_targetposition)
routing algorithm
Private Member Functions
void addsuccessors (final DoubleMatrix1D p_nextjumpnode, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist, final CJumpPoint p_curnode, final DoubleMatrix1D p_target)
Validated successors are added to open list.
void calculateScore (final CJumpPoint p_jumpnode, final DoubleMatrix1D p_target)
Calculates the given node's score using the Manhattan distance formula.
DoubleMatrix1D diagjump (final double p_nextrow, final double p_nextcolumn, final DoubleMatrix1D p_nextnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects)
In order to identify diagonal jump point.
boolean diagonal (final double p_nextrow, final double p_nextcolumn, final double p_row, final double p_col, final double p_hzon, final double p_ver, final ObjectMatrix2D p_objects)
Helper function to identify diagonal jump point.
boolean horizontal (final double p_nextrow, final double p_nextcol, final double p_row, final ObjectMatrix2D p_objects, final double p_value)
Helper function to identify horizontal jump point.
boolean isNotCoordinate (final ObjectMatrix2D p_objects, final double p_row, final double p_column)
To check any point is in the grid environment or out of environment.
boolean isNotNeighbour (final ObjectMatrix2D p_objects, final double p_row, final double p_column, final ArrayList< DoubleMatrix1D > p_closedlist)
Finds the non valid successors of any grid.
boolean isOccupied (final ObjectMatrix2D p_objects, final double p_row, final double p_column)
To check any point in the grid environment is free or occupied.
DoubleMatrix1D jump (final DoubleMatrix1D p_curnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects)
In order to identify individual jump point successors heading in a given direction (run recursively until find a jump point or failure)
void successors (final ObjectMatrix2D p_objects, final CJumpPoint p_curnode, final DoubleMatrix1D p_target, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist)
individual jump point successors are identified
boolean vertical (final double p_nextrow, final double p_nextcol, final double p_col, final ObjectMatrix2D p_objects, final double p_value)
Helper function to identify vertical jump point.
Detailed Description
Definition at line 46 of file CJPSPlus.java.
Member Function Documentation
addsuccessors()
void org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.addsuccessors (final DoubleMatrix1D p_nextjumpnode, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist, final CJumpPoint p_curnode, final DoubleMatrix1D p_target) private
Parameters
p_nextjumpnode successors that need to be validated
p_closedlist the list of coordinate that already explored
p_openlist the set of CJumpPoint that will be explored
p_curnode the current node to search for successors
p_target the goal node
Definition at line 140 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.coordinate(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.fscore().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors().
calculateScore()
void org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore (final CJumpPoint p_jumpnode, final DoubleMatrix1D p_target) private
Parameters
p_jumpnode The node to calculate
p_target the target node
Definition at line 327 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.coordinate(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.gscore(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.hscore(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.parent().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.addsuccessors().
diagjump()
DoubleMatrix1D org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagjump (final double p_nextrow, final double p_nextcolumn, final DoubleMatrix1D p_nextnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects) private
Parameters
p_nextrow row of the next node to search for
p_nextcolumn column of the next node to search for
p_nextnode next node
p_target the goal node
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_objects snapshot of the environment
Returns
diagonal jump point
Definition at line 210 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagonal(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump().
diagonal()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagonal (final double p_nextrow, final double p_nextcolumn, final double p_row, final double p_col, final double p_hzon, final double p_ver, final ObjectMatrix2D p_objects) private
Parameters
p_nextrow row of the next node to search for
p_nextcolumn column of the next node to search for
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_hzon top or bottom direction
p_ver left or right direction
p_objects Snapshot of the environment
Returns
true or false
Definition at line 237 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagjump().
estimatedtime()
final double org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.estimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
Parameters
p_route stream of route landmarks
p_speed estimated speed
Returns
estimated time
Implements org.lightjason.trafficsimulation.simulation.algorithm.routing.IRouting.
Definition at line 91 of file CJPSPlus.java.
horizontal()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.horizontal (final double p_nextrow, final double p_nextcol, final double p_row, final ObjectMatrix2D p_objects, final double p_value) private
Parameters
p_nextrow row of the next node to search for
p_nextcol column of the next node to search for
p_row to increase or decrease row by adding p_row
p_objects Snapshot of the environment
p_value direction
Returns
true or false
Definition at line 258 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump().
initialize()
final IRouting org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.initialize (final ObjectMatrix2D p_objects)
Parameters
p_objects full initialized environment grid (static elements)
Returns
self reference
Implements org.lightjason.trafficsimulation.simulation.algorithm.routing.IRouting.
Definition at line 50 of file CJPSPlus.java.
isNotCoordinate()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate (final ObjectMatrix2D p_objects, final double p_row, final double p_column) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
Returns
return true or false
Definition at line 303 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagonal(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.horizontal(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotNeighbour(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.vertical().
isNotNeighbour()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotNeighbour (final ObjectMatrix2D p_objects, final double p_row, final double p_column, final ArrayList< DoubleMatrix1D > p_closedlist) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
p_closedlist the list of coordinate that already explored
Definition at line 316 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors().
isOccupied()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied (final ObjectMatrix2D p_objects, final double p_row, final double p_column) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
Returns
return true or false
Definition at line 290 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagonal(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.horizontal(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.vertical().
jump()
DoubleMatrix1D org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump (final DoubleMatrix1D p_curnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects) private
Parameters
p_curnode the current node to search for
p_target the goal node
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_objects Snapshot of the environment
Returns
l_nextnode next jump point
Definition at line 167 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagjump(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.horizontal(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.vertical().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.diagjump(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors().
route()
final List<DoubleMatrix1D> org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.route (final ObjectMatrix2D p_objects, final DoubleMatrix1D p_source, final DoubleMatrix1D p_target)
Parameters
p_objects object matrix
p_source current position
p_target target position
Returns
list of tuples of the cellindex
Implements org.lightjason.trafficsimulation.simulation.algorithm.routing.IRouting.
Definition at line 56 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.coordinate(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.parent(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors().
successors()
void org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors (final ObjectMatrix2D p_objects, final CJumpPoint p_curnode, final DoubleMatrix1D p_target, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist) private
Parameters
p_objects Snapshot of the environment
p_curnode the current node to search for successors
p_target the goal node
p_closedlist the list of coordinate that already explored
p_openlist the set of CJumpPoint that will be explored
Definition at line 113 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.addsuccessors(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.coordinate(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotNeighbour(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.route().
vertical()
boolean org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.vertical (final double p_nextrow, final double p_nextcol, final double p_col, final ObjectMatrix2D p_objects, final double p_value) private
Parameters
p_nextrow row of the next node to search for
p_nextcol column of the next node to search for
p_col to increase or decrease column by adding p_col
p_objects Snapshot of the environment
p_value direction
Returns
true or false
Definition at line 275 of file CJPSPlus.java.
References org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isNotCoordinate(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.isOccupied().
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.jump().