LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory Enum Reference
org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory Enum Reference
factory for creating routing objects
Public Member Functions
ERoutingFactory (final IRouting p_routing)
ctor
final IRouting get ()
returns routing object
Public Attributes
JPSPLUS =(new CJPSPlus())
Private Attributes
final IRouting m_routing
routing object
Detailed Description
Definition at line 29 of file ERoutingFactory.java.
Constructor & Destructor Documentation
ERoutingFactory()
org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.ERoutingFactory (final IRouting p_routing)
Parameters
p_routing routing object
Definition at line 43 of file ERoutingFactory.java.
Member Function Documentation
get()
final IRouting org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.get ()
Returns
routing object
Definition at line 53 of file ERoutingFactory.java.
Member Data Documentation
JPSPLUS
org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.JPSPLUS =(new CJPSPlus())
Definition at line 31 of file ERoutingFactory.java.
Referenced by org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.initialize(), and org.lightjason.trafficsimulation.simulation.environment.TestCEnvironment.initilize().
m_routing
final IRouting org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.m_routing private
Definition at line 36 of file ERoutingFactory.java.