# enable / disable logger
logging : false

# show stacktrace on error
stacktrace : true

# agent print call will be shown
agentprint : false

# number of simulation steps - optional if not set, Integer.Max_Value is used
#steps : 2000

# thread-sleep (in milliseconds) time to slow down the simulation speed
threadsleeptime : 100

# screen size of the window - optional with default 1024x1024 pixel
window :
  width : 1024
  height : 1024

# environment (grid) resolution - required
environment :
  cellsize : 16 #pixel
  rows     : 64
  columns  : 64
  routing  : "jpsplus"

# traffic lights
# position in row and col number of the left bottom of the sprite
# durations in 0.1 second
# rotation in degree
# width and height in pixel
trafficlights:
  - vehicles : #west
      startcolor  : green
      startcolorduration : 50
      duration : [ 240, 10, 50, 20]
      position : [ 23, 27 ]
      rotation: 270
      width : 15
      height : 43
  - vehicles : #south
      startcolor  : red
      startcolorduration : 70
      duration : [ 240, 10, 50, 20]
      position : [ 37, 23 ]
      rotation: 0
      width : 15
      height : 43
  - vehicles : #east
      startcolor  : red
      startcolorduration : 150
      duration : [ 240, 10, 50, 20]
      position : [ 41, 37 ]
      rotation: 90
      width : 15
      height : 43
  - vehicles : #north
      startcolor  : red
      startcolorduration : 230
      duration : [ 240, 10, 50, 20]
      position : [ 27, 41 ]
      rotation: 180
      width : 15
      height : 43

# ways
# spriteposition is the left bottom of the sprite [col, row]. It is different from leftbottom and righttop,
# because we rotate the sprite. That will be deleted after changing to new game engine.
# leftbottom and righttop is for the positions in the grid in the environment [col, row]
# rotation in degree
ways:
  - vehicles: #east - forward
      spriteposition : [ 36, 32 ]
      leftbottom : [ 37, 33]
      righttop : [ 64, 36]
      rotation : 0
  - vehicles: #east - backward
      spriteposition : [ 36, 28 ]
      leftbottom : [ 37, 29]
      righttop : [ 64, 32]
      rotation : 0
  - vehicles: #north - forward
      spriteposition : [ 32, 36 ]
      leftbottom : [ 29, 37]
      righttop : [ 32, 64]
      rotation : 90
  - vehicles: #north - backward
      spriteposition : [ 36, 36 ]
      leftbottom : [ 33, 37]
      righttop : [ 36, 64]
      rotation : 90
  - vehicles: #west - forward
      spriteposition : [ 28, 36 ]
      leftbottom : [ 1, 29]
      righttop : [ 28, 32]
      rotation : 180
  - vehicles: #west - backward
      spriteposition : [ 28, 32 ]
      leftbottom : [ 1, 33]
      righttop : [ 28, 36]
      rotation : 180
  - vehicles: #south - forward
      spriteposition : [ 28, 28 ]
      leftbottom : [ 33, 1]
      righttop : [ 36, 28]
      rotation : 270
  - vehicles: #south - backward
      spriteposition : [ 32, 28 ]
      leftbottom : [ 29, 1]
      righttop : [ 32, 28]
      rotation : 270

# leftbottom and righttop of the intersection for the positions in the grid in the environment [col, row]
intersection :
  leftbottom : [ 29, 29]
  righttop : [ 36, 36]

agents :
  - vehicles :
      number : 20
      asl : "vehicle.asl"
      width : 32
      height: 16
      randomgeneratepositions : #the vehicles will be generated randomly on these coordinations
        - position : [ 0, 0 ]
          rotation: 0
        - position : [ 0, 0 ]
          rotation: 90
        - position : [ 0, 0 ]
          rotation: 180
        - position : [ 0, 0 ]
          rotation: 270
