# enable / disable logger
logging : false

# show stacktrace on error
stacktrace : true

# number of simulation steps - optional if not set, Integer.Max_Value is used
#steps : 2000

# thread-sleep (in milliseconds) time to slow down the simulation speed
threadsleeptime : 100

# screen size of the window - optional with default 1024x1024
window :
  width : 1024
  height : 1024

# object counts
counts :
  vehicles : 20

# environment (grid) resolution - required
environment :
  cellsize : 16
  rows     : 64
  columns  : 64

# traffic lights
trafficlights:
  - vehicles : #west
      startcolor  : green
      startcolorduration : 50
      duration : [ 240, 10, 50, 20]
      position : [ 19, 7 ]
      rotation: 270
  - vehicles : #south
      startcolor  : red
      startcolorduration : 70
      duration : [ 240, 10, 50, 20]
      position : [ 28, 5 ]
      rotation: 0
  - vehicles : #east
      startcolor  : red
      startcolorduration : 150
      duration : [ 240, 10, 50, 20]
      position : [ 30, 14 ]
      rotation: 90
  - vehicles : #north
      startcolor  : red
      startcolorduration : 230
      duration : [ 240, 10, 50, 20]
      position : [ 21, 15 ]
      rotation: 180