LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian Class Reference
org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian Class Reference
test pedestrians
Public Member Functions
final void initialize () throws Exception
initialize pedestrian
final void testagentcall () throws Exception
test pedestrian call
Public Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final void loadconfiguration ()
load configuration from yaml file
Static Public Member Functions
static void main (final String[] p_args)
test call
Private Attributes
CPedestrian m_pedestrian
area generator
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final< T extends IObject<?> > T generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments)
runs the object generation proecess
final< T extends IObject<?> > List< T > generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments)
runs the object generation proecess
final void initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception
initialize environment
final void invoketest ()
invoke all test manually
Static Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
static< T extends IAgent<?> Stream< T > executeagent (final Stream< T > p_agent)
executes a stream of agents
static< T extends IAgent<?> T executeagent (final T p_agent)
execute a single agent
Protected Attributes inherited from org.lightjason.trafficsimulation.IBaseTest
IEnvironment m_environment
Static Package Functions inherited from org.lightjason.trafficsimulation.IBaseTest
[static initializer]
Detailed Description
Todo:
create test cases
Definition at line 42 of file TestCPedestrian.java.
Member Function Documentation
initialize()
final void org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.initialize () throws Exception
Exceptions
Exception on initialize environment error
Definition at line 55 of file TestCPedestrian.java.
References org.lightjason.trafficsimulation.IBaseTest.generate(), org.lightjason.trafficsimulation.IBaseTest.initializeenvironment(), org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.JPSPLUS, and org.lightjason.trafficsimulation.simulation.EObjectFactory.PEDESTRIAN.
main()
static void org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.main (final String [] p_args) static
Parameters
p_args command-line arguments
Definition at line 84 of file TestCPedestrian.java.
References org.lightjason.trafficsimulation.IBaseTest.invoketest().
testagentcall()
final void org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.testagentcall () throws Exception
Exceptions
Exception on execution error
Definition at line 67 of file TestCPedestrian.java.
References org.lightjason.trafficsimulation.IBaseTest.executeagent().
Member Data Documentation
m_pedestrian
CPedestrian org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.m_pedestrian private
Definition at line 47 of file TestCPedestrian.java.