LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?> Class Template Reference
org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?> Class Template Reference abstract
base agent object
Classes
class CEnvironmentBeliefbase
environment beliefbase
class IBaseGenerator
base agent generator
Public Member Functions
final boolean equals (final Object p_object)
final int hashCode ()
final Stream< ILiteral > literal (final IObject<?>... p_object)
final Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
final String name ()
final DoubleMatrix1D position ()
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.IObject< T >
Stream< ILiteral > literal (final IObject<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
get literal of the object
String name ()
name of the object
DoubleMatrix1D position ()
position of the object
Protected Member Functions
IBaseObject (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IObject<?>> p_object)
define object literal addons
Protected Attributes
final IEnvironment m_environment
environment reference
DoubleMatrix1D m_position
current position of the agent
Private Attributes
final IView m_external
reference to external beliefbase
final String m_functor
functor definition
final String m_name
name of the object
Static Private Attributes
static final long serialVersionUID = -5112452275211959224L
serial id
Detailed Description
Parameters
<T> IObject
Definition at line 65 of file IBaseObject.java.
Constructor & Destructor Documentation
IBaseObject()
org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.IBaseObject (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position) protected
Parameters
p_configuration agent configuration
p_environment environment reference
p_functor functor of the object literal
p_name name of the object
Definition at line 102 of file IBaseObject.java.
Member Function Documentation
equals()
final boolean org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.equals (final Object p_object)
Definition at line 161 of file IBaseObject.java.
hashCode()
final int org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.hashCode ()
Definition at line 155 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.IBaseObject< T >.equals().
individualliteral()
abstract Stream<ILiteral> org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.individualliteral (final Stream< IObject<?>> p_object) abstract protected
Parameters
p_object calling objects
Returns
literal stream
Referenced by org.lightjason.trafficsimulation.simulation.IBaseObject< T >.literal().
literal() [1/2]
final Stream<ILiteral> org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.literal (final IObject<?>... p_object)
Definition at line 122 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.IBaseObject< T >.literal().
literal() [2/2]
final Stream<ILiteral> org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.literal (final Stream< IObject<?>> p_object)
Definition at line 128 of file IBaseObject.java.
name()
final String org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.name ()
Definition at line 116 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.addarea(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.goal(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.IBaseTrafficLight< CTrafficLightVehicle, ELightColorVehicle >.IBaseTrafficLight(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeatend(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeatstart(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routenext(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeskip().
position()
final DoubleMatrix1D org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.position ()
Definition at line 167 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.move().
Member Data Documentation
m_environment
final IEnvironment org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.m_environment protected
Definition at line 78 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.stationary.trafficlight.IBaseTrafficLight< T extends IBaseTrafficLight<?, ?, L extends Enum<?, >.IGenerator< T extends IBaseTrafficLight<?, ?>.generate(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.route(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeestimatedtime().
m_external
final IView org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.m_external private
Definition at line 90 of file IBaseObject.java.
m_functor
final String org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.m_functor private
Definition at line 82 of file IBaseObject.java.
m_name
final String org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.m_name private
Definition at line 86 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.IBaseObject< T >.name().
m_position
DoubleMatrix1D org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.m_position protected
Definition at line 74 of file IBaseObject.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.goal(), org.lightjason.trafficsimulation.simulation.IBaseObject< T >.position(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.route(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeestimatedtime().
serialVersionUID
final long org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>.serialVersionUID = -5112452275211959224L static private
Definition at line 70 of file IBaseObject.java.