LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?> Class Template Reference
org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?> Class Template Reference abstract
moveable object
Classes
class IGenerator
generator
Public Member Functions
void move (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
move
boolean moveable (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
moveable
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>
final boolean equals (final Object p_object)
final int hashCode ()
final Stream< ILiteral > literal (final IObject<?>... p_object)
final Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
final String name ()
final DoubleMatrix1D position ()
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.IObject< T >
Stream< ILiteral > literal (final IObject<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
get literal of the object
String name ()
name of the object
DoubleMatrix1D position ()
position of the object
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.movable.IMoveable< T >
void move (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
move the object in the grid
boolean moveable (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
check if the object can move in the grid
Protected Member Functions
IBaseMoveable (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position, final DoubleMatrix1D p_size)
ctor
Protected Member Functions inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>
IBaseObject (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IObject<?>> p_object)
define object literal addons
Static Protected Attributes
static final String GROUP = "moveable"
group ov all agents
Private Member Functions
Stream< Pair< Integer, Integer > > cells (final DoubleMatrix1D p_position)
get a stream of cells from position
DoubleMatrix1D goal ()
returns the goal-position
List< DoubleMatrix1D > route (final Number p_row, final Number p_column)
calculates a new route
void routeatend (final Number p_row, final Number p_column)
route calculation and add landmarks at the end
void routeatstart (final Number p_row, final Number p_column)
route calculation and add landmarks at the beginning
double routeestimatedtime ()
calculates the estimated time by the current speed of the current route
void routenext ()
skips the current goal-position of the routing queue
void routeskip (final Number p_value)
skips the current n-elements of the routing queue
Private Attributes
final List< DoubleMatrix1D > m_route = new ArrayList<>()
list of landmarks (route)
AtomicInteger m_speed = new AtomicInteger(1)
speed definition
Static Private Attributes
static final long serialVersionUID = -807753696520276249L
serial id
Additional Inherited Members
Protected Attributes inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< T extends IObject<?>
final IEnvironment m_environment
environment reference
DoubleMatrix1D m_position
current position of the agent
Detailed Description
Todo:
implement moving
can we create a main generate method for vehicles and pedestrian?
Definition at line 53 of file IBaseMoveable.java.
Constructor & Destructor Documentation
IBaseMoveable()
org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.IBaseMoveable (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position, final DoubleMatrix1D p_size) protected
Parameters
p_configuration agent configuration
Definition at line 80 of file IBaseMoveable.java.
Member Function Documentation
cells()
Stream<Pair<Integer, Integer> > org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.cells (final DoubleMatrix1D p_position) private
Parameters
p_position position
Returns
cells
Todo:
can it be optimized with refactoring inttuple with automatic cast?
should be static?
Definition at line 94 of file IBaseMoveable.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.move(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.moveable().
goal()
DoubleMatrix1D org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.goal () private
Returns
position
Definition at line 145 of file IBaseMoveable.java.
move()
void org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.move (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
Todo:
should be static ?
Definition at line 121 of file IBaseMoveable.java.
moveable()
boolean org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.moveable (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
Todo:
should be static ?
Definition at line 109 of file IBaseMoveable.java.
route()
List<DoubleMatrix1D> org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.route (final Number p_row, final Number p_column) private
Parameters
p_row target row position
p_column target column position
Returns
route list
Definition at line 136 of file IBaseMoveable.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeatend(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeatstart().
routeatend()
void org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.routeatend (final Number p_row, final Number p_column) private
Parameters
p_row row position
p_column column position
Definition at line 176 of file IBaseMoveable.java.
routeatstart()
void org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.routeatstart (final Number p_row, final Number p_column) private
Parameters
p_row row position
p_column column position
Definition at line 163 of file IBaseMoveable.java.
routeestimatedtime()
double org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.routeestimatedtime () private
Returns
time
Definition at line 215 of file IBaseMoveable.java.
routenext()
void org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.routenext () private
Definition at line 186 of file IBaseMoveable.java.
routeskip()
void org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.routeskip (final Number p_value) private
Parameters
p_value number of elements
Definition at line 199 of file IBaseMoveable.java.
Member Data Documentation
GROUP
final String org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.GROUP = "moveable" static protected
Definition at line 58 of file IBaseMoveable.java.
m_route
final List<DoubleMatrix1D> org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.m_route = new ArrayList<>() private
Definition at line 72 of file IBaseMoveable.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeatend(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeestimatedtime(), org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routenext(), and org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeskip().
m_speed
AtomicInteger org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.m_speed = new AtomicInteger(1) private
Bug:
must be set on initialize to zero, current set to one for testing
Definition at line 68 of file IBaseMoveable.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeestimatedtime().
serialVersionUID
final long org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< T extends IBaseMoveable<?>.serialVersionUID = -807753696520276249L static private
Definition at line 62 of file IBaseMoveable.java.