LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint Class Reference
org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint Class Reference
jump-point with a static class "static" means that the class can exists without the CJPSPlus object "final" no inheritance can be create
Static Public Attributes
static final CJumpPoint ZERO = new CJumpPoint()
for avoid zero-jump-points we create exactly one
Package Functions
CJumpPoint (final DoubleMatrix1D p_coordinate, final CJumpPoint p_parent)
ctor
final DoubleMatrix1D coordinate ()
getter for coordinate
final double fscore ()
getter for f_score
final double gscore ()
getter for g-score
final CJumpPoint gscore (final double p_gscore)
setter for g_score
final CJumpPoint hscore (final double p_hscore)
setter for h_score
final CJumpPoint parent ()
getter for parent
Private Member Functions
CJumpPoint ()
ctor - with default values
Private Attributes
final DoubleMatrix1D m_coordinate
position
double m_gscore
jump-point g-score value
double m_hscore
jump-point h-score value
CJumpPoint m_parent
parent node of current JumpPoint
Detailed Description
Definition at line 358 of file CJPSPlus.java.
Constructor & Destructor Documentation
CJumpPoint() [1/2]
org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.CJumpPoint () private
Definition at line 388 of file CJPSPlus.java.
CJumpPoint() [2/2]
org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.CJumpPoint (final DoubleMatrix1D p_coordinate, final CJumpPoint p_parent) package
Parameters
p_coordinate postion value
p_parent parent of the current jump point
Definition at line 399 of file CJPSPlus.java.
Member Function Documentation
coordinate()
final DoubleMatrix1D org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.coordinate () package
Returns
coordinate
Definition at line 410 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.addsuccessors(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore(), org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.route(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.successors().
fscore()
final double org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.fscore () package
Returns
f-score
Definition at line 430 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.addsuccessors(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CCompareJumpPoint.compare().
gscore() [1/2]
final double org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.gscore () package
Returns
g-score
Definition at line 420 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore().
gscore() [2/2]
final CJumpPoint org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.gscore (final double p_gscore) package
Returns
CJumpPoint
Definition at line 450 of file CJPSPlus.java.
hscore()
final CJumpPoint org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.hscore (final double p_hscore) package
Returns
CJumpPoint
Definition at line 461 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore().
parent()
final CJumpPoint org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.parent () package
Returns
parent
Definition at line 440 of file CJPSPlus.java.
Referenced by org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.calculateScore(), and org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.route().
Member Data Documentation
m_coordinate
final DoubleMatrix1D org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.m_coordinate private
Definition at line 383 of file CJPSPlus.java.
m_gscore
double org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.m_gscore private
Definition at line 368 of file CJPSPlus.java.
m_hscore
double org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.m_hscore private
Definition at line 373 of file CJPSPlus.java.
m_parent
CJumpPoint org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.m_parent private
Definition at line 378 of file CJPSPlus.java.
ZERO
final CJumpPoint org.lightjason.trafficsimulation.simulation.algorithm.routing.CJPSPlus.CJumpPoint.ZERO = new CJumpPoint() static
Definition at line 363 of file CJPSPlus.java.