LightJason - TrafficSimulation: org.lightjason.trafficsimulation.CConfiguration Class Reference
org.lightjason.trafficsimulation.CConfiguration Class Reference
configuration and initialization of all simulation objects
Public Member Functions
boolean equals (final Object p_object)
final< T > T get (final String... p_path)
returns a configuration value
final< T > T getOrDefault (final T p_default, final String... p_path)
returns a configuration value or on not existing the default value
final int hashCode ()
final CConfiguration loadfile (final String p_path)
loads the configuration
final CConfiguration loadstring (final String p_yaml)
loads the configuration from a string
final String toString ()
final IView view (final IView p_parent)
returns a beliefbase view
Static Public Member Functions
static String createdefault () throws IOException
creates the default configuration
Static Public Attributes
static final CConfiguration INSTANCE = new CConfiguration()
singleton instance
Private Member Functions
CConfiguration ()
ctor
CConfiguration set (final Object p_data)
push data to the internal map
Static Private Member Functions
static Stream< Map.Entry< String, Object > > mapstream (final Map< String, Object > p_map, final String p_prefix)
static Object maptolowercase (final Object p_value)
convert all map keys to lower-case
static InputStream orDefaultPath (final String p_path) throws FileNotFoundException
set default path
static Stream< Map.Entry< String, Object > > recursivedescent (final Map< String, ?> p_map, final int p_index, final String... p_path)
recursive descent of a given path
Private Attributes
final Map< String, Object > m_configuration = new TreeMap<>(String.CASE_INSENSITIVE_ORDER)
map with configuration data
Static Private Attributes
static final String BELIEFBASE = "config"
name of the beliefbase
Detailed Description
Bug:
refactor
Definition at line 54 of file CConfiguration.java.
Constructor & Destructor Documentation
CConfiguration()
org.lightjason.trafficsimulation.CConfiguration.CConfiguration () private
Definition at line 74 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.equals().
Member Function Documentation
createdefault()
static String org.lightjason.trafficsimulation.CConfiguration.createdefault () throws IOException static
Returns
full path
Exceptions
IOException on any io error
Definition at line 197 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CMain.main().
equals()
boolean org.lightjason.trafficsimulation.CConfiguration.equals (final Object p_object)
Definition at line 165 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.CConfiguration(), and org.lightjason.trafficsimulation.CConfiguration.hashCode().
get()
final<T> T org.lightjason.trafficsimulation.CConfiguration.get (final String... p_path)
Parameters
p_path path of the element
Template Parameters
T returning type
Returns
value or null
Definition at line 223 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.m_configuration, and org.lightjason.trafficsimulation.CConfiguration.recursivedescent().
getOrDefault()
final<T> T org.lightjason.trafficsimulation.CConfiguration.getOrDefault (final T p_default, final String... p_path)
Parameters
p_default default value
p_path path of the element
Template Parameters
T returning type
Returns
value / default vaue
Definition at line 247 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.m_configuration, and org.lightjason.trafficsimulation.CConfiguration.recursivedescent().
hashCode()
final int org.lightjason.trafficsimulation.CConfiguration.hashCode ()
Definition at line 159 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.equals().
loadfile()
final CConfiguration org.lightjason.trafficsimulation.CConfiguration.loadfile (final String p_path)
Parameters
p_path path elements
Returns
self reference
Definition at line 85 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.orDefaultPath().
Referenced by org.lightjason.trafficsimulation.IBaseTest.loadconfiguration(), and org.lightjason.trafficsimulation.CMain.main().
loadstring()
final CConfiguration org.lightjason.trafficsimulation.CConfiguration.loadstring (final String p_yaml)
Parameters
p_yaml yaml string
Returns
self reference
Definition at line 108 of file CConfiguration.java.
mapstream()
static Stream<Map.Entry<String, Object> > org.lightjason.trafficsimulation.CConfiguration.mapstream (final Map< String, Object > p_map, final String p_prefix) static private
Parameters
p_map map
Returns
stream of all items within the map
Todo:
fix path name with full path
Definition at line 296 of file CConfiguration.java.
maptolowercase()
static Object org.lightjason.trafficsimulation.CConfiguration.maptolowercase (final Object p_value) static private
Parameters
p_value any value
Returns
object return
Definition at line 140 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.set().
orDefaultPath()
static InputStream org.lightjason.trafficsimulation.CConfiguration.orDefaultPath (final String p_path) throws FileNotFoundException static private
Parameters
p_path path or null / empty
Returns
default path on empty or input path
Definition at line 183 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.loadfile().
recursivedescent()
static Stream<Map.Entry<String, Object> > org.lightjason.trafficsimulation.CConfiguration.recursivedescent (final Map< String, ?> p_map, final int p_index, final String... p_path) static private
Parameters
p_map start map
p_index index of path
p_path path of the item
Returns
stream of items
Definition at line 273 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.get(), and org.lightjason.trafficsimulation.CConfiguration.getOrDefault().
set()
CConfiguration org.lightjason.trafficsimulation.CConfiguration.set (final Object p_data) private
Parameters
p_data input data
Returns
self reference
Definition at line 121 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.m_configuration, and org.lightjason.trafficsimulation.CConfiguration.maptolowercase().
toString()
final String org.lightjason.trafficsimulation.CConfiguration.toString ()
Definition at line 171 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.m_configuration.
view()
final IView org.lightjason.trafficsimulation.CConfiguration.view (final IView p_parent)
Parameters
p_parent parent view
Returns
new view
Definition at line 258 of file CConfiguration.java.
References org.lightjason.trafficsimulation.CConfiguration.BELIEFBASE, and org.lightjason.trafficsimulation.CConfiguration.m_configuration.
Referenced by org.lightjason.trafficsimulation.simulation.environment.CEnvironment.CGenerator.generate().
Member Data Documentation
BELIEFBASE
final String org.lightjason.trafficsimulation.CConfiguration.BELIEFBASE = "config" static private
Definition at line 63 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.view().
INSTANCE
final CConfiguration org.lightjason.trafficsimulation.CConfiguration.INSTANCE = new CConfiguration() static
Definition at line 59 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.ui.CHTTPServer.CHTTPServer(), org.lightjason.trafficsimulation.ui.CHTTPServer.execute(), org.lightjason.trafficsimulation.simulation.environment.CEnvironment.CGenerator.generate(), org.lightjason.trafficsimulation.IBaseTest.loadconfiguration(), and org.lightjason.trafficsimulation.CMain.main().
m_configuration
final Map<String, Object> org.lightjason.trafficsimulation.CConfiguration.m_configuration = new TreeMap<>(String.CASE_INSENSITIVE_ORDER) private
Definition at line 67 of file CConfiguration.java.
Referenced by org.lightjason.trafficsimulation.CConfiguration.get(), org.lightjason.trafficsimulation.CConfiguration.getOrDefault(), org.lightjason.trafficsimulation.CConfiguration.set(), org.lightjason.trafficsimulation.CConfiguration.toString(), and org.lightjason.trafficsimulation.CConfiguration.view().