LightJason - TrafficSimulation: org.lightjason.trafficsimulation.IBaseTest Class Reference
org.lightjason.trafficsimulation.IBaseTest Class Reference abstract
base test
Public Member Functions
final void loadconfiguration ()
load configuration from yaml file
Protected Member Functions
final< T extends IObject<?> > T generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments)
runs the object generation proecess
final< T extends IObject<?> > List< T > generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments)
runs the object generation proecess
final void initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception
initialize environment
final void invoketest ()
invoke all test manually
Static Protected Member Functions
static< T extends IAgent<?> Stream< T > executeagent (final Stream< T > p_agent)
executes a stream of agents
static< T extends IAgent<?> T executeagent (final T p_agent)
execute a single agent
Protected Attributes
IEnvironment m_environment
Static Package Functions
[static initializer]
Private Member Functions
Set< Method > before ()
reads the before annotated methods
void execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments)
invokes the method within the current object context
void invoke (final Method p_method, final Set< Method > p_before)
invoke method and read if possible the data-provider
Private Attributes
final Set< IAction > m_actions
final Map< String, IAgent<?> > m_agents = new ConcurrentHashMap<>()
Detailed Description
Todo:
fix documentation
Definition at line 63 of file IBaseTest.java.
Member Function Documentation
[static initializer]()
org.lightjason.trafficsimulation.IBaseTest.[static initializer] () static package
before()
Set<Method> org.lightjason.trafficsimulation.IBaseTest.before () private
Returns
optional before method
Definition at line 320 of file IBaseTest.java.
Referenced by org.lightjason.trafficsimulation.IBaseTest.invoketest().
execute()
void org.lightjason.trafficsimulation.IBaseTest.execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments) private
Parameters
p_method method
p_before before method
p_arguments optional arguments
Definition at line 275 of file IBaseTest.java.
Referenced by org.lightjason.trafficsimulation.IBaseTest.invoke().
executeagent() [1/2]
static <T extends IAgent<?> Stream<T> org.lightjason.trafficsimulation.IBaseTest.executeagent (final Stream< T > p_agent) static protected
Parameters
p_agent agent stream
Template Parameters
T agent type
Returns
agent stream
Definition at line 192 of file IBaseTest.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.test(), and org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.testagentcall().
executeagent() [2/2]
static <T extends IAgent<?> T org.lightjason.trafficsimulation.IBaseTest.executeagent (final T p_agent) static protected
Parameters
p_agent agent
Template Parameters
T agent type
Returns
agent
Definition at line 204 of file IBaseTest.java.
generate()
final<T extends IObject<?> > T org.lightjason.trafficsimulation.IBaseTest.generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments) protected
Parameters
p_file filename
p_factory generator
p_arguments generating arguments
<T> IObject
Returns
IObject
Definition at line 127 of file IBaseTest.java.
References org.lightjason.trafficsimulation.simulation.EObjectFactory.generate(), and org.lightjason.trafficsimulation.IBaseTest.m_environment.
Referenced by org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.initialize(), and org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.initialize().
generatemultiple()
final<T extends IObject<?> > List<T> org.lightjason.trafficsimulation.IBaseTest.generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments) protected
Parameters
p_file filename
p_factory generator
p_number number of agents
p_arguments generating arguments
<T> IObject
Returns
List of IObjects
Definition at line 160 of file IBaseTest.java.
References org.lightjason.trafficsimulation.simulation.EObjectFactory.generate(), and org.lightjason.trafficsimulation.IBaseTest.m_environment.
initializeenvironment()
final void org.lightjason.trafficsimulation.IBaseTest.initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception protected
Note
must be called on the before-test method
Exceptions
Exception on any error
Definition at line 90 of file IBaseTest.java.
References org.lightjason.trafficsimulation.simulation.EObjectFactory.ENVIRONMENT.
Referenced by org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.initialize(), org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.initialize(), and org.lightjason.trafficsimulation.simulation.environment.TestCEnvironment.initilize().
invoke()
void org.lightjason.trafficsimulation.IBaseTest.invoke (final Method p_method, final Set< Method > p_before) private
Parameters
p_method method
p_before before method
Definition at line 239 of file IBaseTest.java.
References org.lightjason.trafficsimulation.IBaseTest.execute().
Referenced by org.lightjason.trafficsimulation.IBaseTest.invoketest().
invoketest()
final void org.lightjason.trafficsimulation.IBaseTest.invoketest () protected
Definition at line 223 of file IBaseTest.java.
References org.lightjason.trafficsimulation.IBaseTest.before(), and org.lightjason.trafficsimulation.IBaseTest.invoke().
Referenced by org.lightjason.trafficsimulation.simulation.virtual .TestCArea.main(), org.lightjason.trafficsimulation.simulation.environment.TestCEnvironment.main(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.main(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.main(), org.lightjason.trafficsimulation.simulation.movable.TestCPedestrian.main(), org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.main(), and org.lightjason.trafficsimulation.simulation.movable.TestCViewPedstrian.main().
loadconfiguration()
final void org.lightjason.trafficsimulation.IBaseTest.loadconfiguration ()
Definition at line 113 of file IBaseTest.java.
References org.lightjason.trafficsimulation.CConfiguration.INSTANCE, org.lightjason.trafficsimulation.CConfiguration.loadfile(), and org.lightjason.trafficsimulation.CCommon.PACKAGEPATH.
Member Data Documentation
m_actions
final Set<IAction> org.lightjason.trafficsimulation.IBaseTest.m_actions private
Initial value:
= Stream.concat(
                                                Stream.of(
                                                    new CSend( m_agents ),
                                                    new CBroadcast( m_agents )
                                                ),
                                                CCommon.actionsFromPackage()
                                           ).collect( Collectors.toSet() )
Definition at line 69 of file IBaseTest.java.
m_agents
final Map<String, IAgent<?> > org.lightjason.trafficsimulation.IBaseTest.m_agents = new ConcurrentHashMap<>() private
Definition at line 67 of file IBaseTest.java.
m_environment
IEnvironment org.lightjason.trafficsimulation.IBaseTest.m_environment protected
Definition at line 65 of file IBaseTest.java.
Referenced by org.lightjason.trafficsimulation.IBaseTest.generate(), org.lightjason.trafficsimulation.IBaseTest.generatemultiple(), org.lightjason.trafficsimulation.simulation.environment.TestCEnvironment.testEnvironmentCall(), and org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.testMoving().