LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle Class Reference
org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle Class Reference
test vehicles traffic light
Public Member Functions
final void initialize () throws Exception
initialize vehicle light
final void test () throws Exception
vehicle traffic light call test
Public Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final void loadconfiguration ()
load configuration from yaml file
Static Public Member Functions
static void main (final String[] p_args) throws Exception
main method
Private Attributes
CTrafficLightVehicle m_vehiclelight
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final< T extends IObject<?> > T generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments)
runs the object generation proecess
final< T extends IObject<?> > List< T > generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments)
runs the object generation proecess
final void initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception
initialize environment
final void invoketest ()
invoke all test manually
Static Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
static< T extends IAgent<?> Stream< T > executeagent (final Stream< T > p_agent)
executes a stream of agents
static< T extends IAgent<?> T executeagent (final T p_agent)
execute a single agent
Protected Attributes inherited from org.lightjason.trafficsimulation.IBaseTest
IEnvironment m_environment
Static Package Functions inherited from org.lightjason.trafficsimulation.IBaseTest
[static initializer]
Detailed Description
Definition at line 40 of file TestCTrafficLightVehicle.java.
Member Function Documentation
initialize()
final void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.initialize () throws Exception
Exceptions
Exception on any error
Definition at line 51 of file TestCTrafficLightVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.generate(), org.lightjason.trafficsimulation.IBaseTest.initializeenvironment(), org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.JPSPLUS, and org.lightjason.trafficsimulation.simulation.EObjectFactory.VEHICLE_TRAFFICLIGHT.
main()
static void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.main (final String [] p_args) throws Exception static
Parameters
p_args args
Exceptions
Exception on any error
Definition at line 79 of file TestCTrafficLightVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.invoketest().
test()
final void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.test () throws Exception
Exceptions
Exception on execution error
Definition at line 64 of file TestCTrafficLightVehicle.java.
Member Data Documentation
m_vehiclelight
CTrafficLightVehicle org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightVehicle.m_vehiclelight private
Definition at line 43 of file TestCTrafficLightVehicle.java.