LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian Class Reference
org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian Class Reference
test pedestrian traffic light
Public Member Functions
final void initialize () throws Exception
initialize traffic light
final void test () throws Exception
pedestrian test
Public Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final void loadconfiguration ()
load configuration from yaml file
Static Public Member Functions
static void main (final String[] p_args)
main method
Private Attributes
CTrafficLightPedestrian m_pedestrianlight
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final< T extends IObject<?> > T generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments)
runs the object generation proecess
final< T extends IObject<?> > List< T > generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments)
runs the object generation proecess
final void initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception
initialize environment
final void invoketest ()
invoke all test manually
Static Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
static< T extends IAgent<?> Stream< T > executeagent (final Stream< T > p_agent)
executes a stream of agents
static< T extends IAgent<?> T executeagent (final T p_agent)
execute a single agent
Protected Attributes inherited from org.lightjason.trafficsimulation.IBaseTest
IEnvironment m_environment
Static Package Functions inherited from org.lightjason.trafficsimulation.IBaseTest
[static initializer]
Detailed Description
Definition at line 40 of file TestCTrafficLightPedestrian.java.
Member Function Documentation
initialize()
final void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.initialize () throws Exception
Exceptions
Exception is thrown on any error
Definition at line 51 of file TestCTrafficLightPedestrian.java.
References org.lightjason.trafficsimulation.IBaseTest.generate(), org.lightjason.trafficsimulation.IBaseTest.initializeenvironment(), org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.JPSPLUS, and org.lightjason.trafficsimulation.simulation.EObjectFactory.PEDESTRIAN_TRAFFICLIGHT.
main()
static void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.main (final String [] p_args) static
Parameters
p_args args
Definition at line 81 of file TestCTrafficLightPedestrian.java.
References org.lightjason.trafficsimulation.IBaseTest.invoketest().
test()
final void org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.test () throws Exception
Exceptions
Exception on execution error
Definition at line 68 of file TestCTrafficLightPedestrian.java.
Member Data Documentation
m_pedestrianlight
CTrafficLightPedestrian org.lightjason.trafficsimulation.simulation.stationary.trafficlight.TestCTrafficLightPedestrian.m_pedestrianlight private
Definition at line 43 of file TestCTrafficLightPedestrian.java.