LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.virtual .CArea Class Reference
org.lightjason.trafficsimulation.simulation.virtual .CArea Class Reference
area class
Public Member Functions
void addPhysical (final IMoveable<?> p_physical)
add a physical agent to the area
CArea call () throws Exception
boolean isInside (final DoubleMatrix1D p_position)
check if a position is inside the area
String type ()
get area type
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< CArea >
final boolean equals (final Object p_object)
final int hashCode ()
final Stream< ILiteral > literal (final IObject<?>... p_object)
final Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
final String name ()
final DoubleMatrix1D position ()
Protected Member Functions
Stream< ILiteral > individualliteral (final Stream< IObject<?>> p_object)
Protected Member Functions inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< CArea >
IBaseObject (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IObject<?>> p_object)
define object literal addons
Private Member Functions
CArea (final IAgentConfiguration< CArea > p_configuration, final IEnvironment p_environment, final String p_name, final List< CRawTerm<?>> p_position, final boolean p_passable, final String p_type, final List< CRawTerm<?>> p_directions)
ctor
Private Attributes
final Stream< EDirection > m_directions
in which direction one can move in this area
final boolean m_passable
if the area is passable
final Set< IMoveable<?> > m_physical = new HashSet<>()
a set of the physical agents in the area
final String m_type
the type of area
Static Private Attributes
static final AtomicLong COUNTER = new AtomicLong()
static final String FUNCTOR = "area"
literal functor
static final long serialVersionUID = -3024951595684069650L
serial id
Additional Inherited Members
Protected Attributes inherited from org.lightjason.trafficsimulation.simulation.IBaseObject< CArea >
final IEnvironment m_environment
environment reference
DoubleMatrix1D m_position
current position of the agent
Detailed Description
Definition at line 55 of file CArea.java.
Constructor & Destructor Documentation
CArea()
org.lightjason.trafficsimulation.simulation.virtual .CArea.CArea (final IAgentConfiguration< CArea > p_configuration, final IEnvironment p_environment, final String p_name, final List< CRawTerm<?>> p_position, final boolean p_passable, final String p_type, final List< CRawTerm<?>> p_directions) private
Parameters
p_configuration agent configuration
p_environment environment reference
p_name name of the object
Definition at line 93 of file CArea.java.
Referenced by org.lightjason.trafficsimulation.simulation.virtual .CArea.CGenerator.generate().
Member Function Documentation
addPhysical()
void org.lightjason.trafficsimulation.simulation.virtual .CArea.addPhysical (final IMoveable<?> p_physical)
Parameters
p_physical physical agent
Definition at line 129 of file CArea.java.
References org.lightjason.trafficsimulation.simulation.virtual .CArea.isInside().
call()
CArea org.lightjason.trafficsimulation.simulation.virtual .CArea.call () throws Exception
Definition at line 139 of file CArea.java.
References org.lightjason.trafficsimulation.simulation.virtual .CArea.call(), and org.lightjason.trafficsimulation.simulation.virtual .CArea.isInside().
Referenced by org.lightjason.trafficsimulation.simulation.virtual .CArea.call().
individualliteral()
Stream<ILiteral> org.lightjason.trafficsimulation.simulation.virtual .CArea.individualliteral (final Stream< IObject<?>> p_object) protected
Definition at line 103 of file CArea.java.
isInside()
boolean org.lightjason.trafficsimulation.simulation.virtual .CArea.isInside (final DoubleMatrix1D p_position)
Parameters
p_position position
Returns
boolean
Definition at line 118 of file CArea.java.
References org.lightjason.trafficsimulation.simulation.IBaseObject< CArea >.m_position.
Referenced by org.lightjason.trafficsimulation.simulation.virtual .CArea.addPhysical(), and org.lightjason.trafficsimulation.simulation.virtual .CArea.call().
type()
String org.lightjason.trafficsimulation.simulation.virtual .CArea.type ()
Returns
type
Definition at line 154 of file CArea.java.
References org.lightjason.trafficsimulation.simulation.virtual .CArea.m_type.
Member Data Documentation
COUNTER
final AtomicLong org.lightjason.trafficsimulation.simulation.virtual .CArea.COUNTER = new AtomicLong() static private
Definition at line 68 of file CArea.java.
FUNCTOR
final String org.lightjason.trafficsimulation.simulation.virtual .CArea.FUNCTOR = "area" static private
Definition at line 64 of file CArea.java.
m_directions
final Stream<EDirection> org.lightjason.trafficsimulation.simulation.virtual .CArea.m_directions private
Definition at line 80 of file CArea.java.
m_passable
final boolean org.lightjason.trafficsimulation.simulation.virtual .CArea.m_passable private
Definition at line 72 of file CArea.java.
m_physical
final Set<IMoveable<?> > org.lightjason.trafficsimulation.simulation.virtual .CArea.m_physical = new HashSet<>() private
Definition at line 84 of file CArea.java.
m_type
final String org.lightjason.trafficsimulation.simulation.virtual .CArea.m_type private
Definition at line 76 of file CArea.java.
Referenced by org.lightjason.trafficsimulation.simulation.virtual .CArea.type().
serialVersionUID
final long org.lightjason.trafficsimulation.simulation.virtual .CArea.serialVersionUID = -3024951595684069650L static private
Definition at line 60 of file CArea.java.