LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.movable.TestCVehicle Class Reference
org.lightjason.trafficsimulation.simulation.movable.TestCVehicle Class Reference
test vehicle
Public Member Functions
final void initialize () throws Exception
initialize vehicle
final void test ()
vehicle test
final void testMoving ()
test moving a vehicle
Public Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final void loadconfiguration ()
load configuration from yaml file
Static Public Member Functions
static void main (final String[] p_args)
main method
Private Attributes
CVehicle m_vehicle
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
final< T extends IObject<?> > T generate (final String p_file, final EObjectFactory p_factory, final Object... p_arguments)
runs the object generation proecess
final< T extends IObject<?> > List< T > generatemultiple (final String p_file, final EObjectFactory p_factory, final int p_number, final Object... p_arguments)
runs the object generation proecess
final void initializeenvironment (final int p_column, final int p_row, final double p_size, final IRouting p_routing) throws Exception
initialize environment
final void invoketest ()
invoke all test manually
Static Protected Member Functions inherited from org.lightjason.trafficsimulation.IBaseTest
static< T extends IAgent<?> Stream< T > executeagent (final Stream< T > p_agent)
executes a stream of agents
static< T extends IAgent<?> T executeagent (final T p_agent)
execute a single agent
Protected Attributes inherited from org.lightjason.trafficsimulation.IBaseTest
IEnvironment m_environment
Static Package Functions inherited from org.lightjason.trafficsimulation.IBaseTest
[static initializer]
Detailed Description
Todo:
create test cases
Definition at line 42 of file TestCVehicle.java.
Member Function Documentation
initialize()
final void org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.initialize () throws Exception
Exceptions
Exception on any error
Definition at line 53 of file TestCVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.generate(), org.lightjason.trafficsimulation.IBaseTest.initializeenvironment(), org.lightjason.trafficsimulation.simulation.algorithm.routing.ERoutingFactory.JPSPLUS, and org.lightjason.trafficsimulation.simulation.EObjectFactory.VEHICLE.
main()
static void org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.main (final String [] p_args) static
Parameters
p_args args
Definition at line 89 of file TestCVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.invoketest().
test()
final void org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.test ()
Definition at line 64 of file TestCVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.executeagent().
testMoving()
final void org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.testMoving ()
Definition at line 77 of file TestCVehicle.java.
References org.lightjason.trafficsimulation.IBaseTest.m_environment, and org.lightjason.trafficsimulation.simulation.environment.IEnvironment.move().
Member Data Documentation
m_vehicle
CVehicle org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.m_vehicle private
Definition at line 45 of file TestCVehicle.java.