LightJason - TrafficSimulation: org.lightjason.trafficsimulation.runtime.CRuntime Class Reference
org.lightjason.trafficsimulation.runtime.CRuntime Class Reference
runtime class for execution an experiment
Public Member Functions
final IExperiment execute (final IExperiment p_experiment)
execute an experiment
Static Public Attributes
static final CRuntime INSTANCE = new CRuntime()
singleton instance
Private Member Functions
CRuntime ()
private ctor
Static Private Member Functions
static void executewithlogging (final Callable<?> p_callable)
executs a callable object and logs the errors
static< T > Stream< T > parallel (final Stream< T > p_stream, final boolean p_parallel)
executes a stream in parallel
Detailed Description
Definition at line 34 of file CRuntime.java.
Constructor & Destructor Documentation
CRuntime()
org.lightjason.trafficsimulation.runtime.CRuntime.CRuntime () private
Definition at line 44 of file CRuntime.java.
Member Function Documentation
execute()
final IExperiment org.lightjason.trafficsimulation.runtime.CRuntime.execute (final IExperiment p_experiment)
Parameters
p_experiment experiment
Returns
experiment
Todo:
execution should be terminate by an agent call, not only on simulaiton steps
Definition at line 56 of file CRuntime.java.
References org.lightjason.trafficsimulation.runtime.IExperiment.agents(), org.lightjason.trafficsimulation.runtime.CRuntime.executewithlogging(), org.lightjason.trafficsimulation.runtime.IExperiment.parallel(), org.lightjason.trafficsimulation.runtime.CRuntime.parallel(), and org.lightjason.trafficsimulation.runtime.IExperiment.simulationsteps().
executewithlogging()
static void org.lightjason.trafficsimulation.runtime.CRuntime.executewithlogging (final Callable<?> p_callable) static private
Parameters
p_callable callable object
Bug:
log is missing
Definition at line 86 of file CRuntime.java.
Referenced by org.lightjason.trafficsimulation.runtime.CRuntime.execute().
parallel()
static <T> Stream<T> org.lightjason.trafficsimulation.runtime.CRuntime.parallel (final Stream< T > p_stream, final boolean p_parallel) static private
Parameters
p_stream object stream
p_parallel parallel execution
Returns
stream
Definition at line 75 of file CRuntime.java.
Referenced by org.lightjason.trafficsimulation.runtime.CRuntime.execute().
Member Data Documentation
INSTANCE
final CRuntime org.lightjason.trafficsimulation.runtime.CRuntime.INSTANCE = new CRuntime() static
Definition at line 39 of file CRuntime.java.