LightJason - TrafficSimulation: org.lightjason.trafficsimulation.CCommon Class Reference
org.lightjason.trafficsimulation.CCommon Class Reference
common class
Static Public Member Functions
static URL getResourceURL (final String p_file) throws MalformedURLException, URISyntaxException
returns a file from a resource e.g.
static URL getResourceURL (final File p_file) throws MalformedURLException, URISyntaxException
returns a file from a resource e.g.
static Stream< Pair< Integer, Integer > > inttupelstream (final int p_firststart, final int p_firstend, final int p_secondstart, final int p_secondend)
creates an int-pair-stream of an element
Static Public Attributes
static final String PACKAGEPATH = "org/lightjason/trafficsimulation/"
package path
Private Member Functions
CCommon ()
constructor
Detailed Description
Bug:
clean-up
Definition at line 43 of file CCommon.java.
Constructor & Destructor Documentation
CCommon()
org.lightjason.trafficsimulation.CCommon.CCommon () private
Definition at line 53 of file CCommon.java.
Member Function Documentation
getResourceURL() [1/2]
static URL org.lightjason.trafficsimulation.CCommon.getResourceURL (final String p_file) throws MalformedURLException, URISyntaxException static
Jar file
Parameters
p_file file
Returns
URL of file or null
Exceptions
MalformedURLException on incorrect URL
URISyntaxException on incorrect URI syntax
Definition at line 98 of file CCommon.java.
References org.lightjason.trafficsimulation.CCommon.getResourceURL().
Referenced by org.lightjason.trafficsimulation.CCommon.getResourceURL().
getResourceURL() [2/2]
static URL org.lightjason.trafficsimulation.CCommon.getResourceURL (final File p_file) throws MalformedURLException, URISyntaxException static
Jar file
Parameters
p_file file relative to the CMain
Returns
URL of file or null
Exceptions
MalformedURLException on incorrect URL
URISyntaxException on incorrect URI syntax
Definition at line 112 of file CCommon.java.
inttupelstream()
static Stream<Pair<Integer, Integer> > org.lightjason.trafficsimulation.CCommon.inttupelstream (final int p_firststart, final int p_firstend, final int p_secondstart, final int p_secondend) static
Parameters
p_object object but position must be return a vector with 4 elements
Returns
int-pair-stream creates an int-pair-stream
Parameters
p_firststart start value of first component
p_firstend end (inclusive) of first component
p_secondstart start value of second component
p_secondend end (inclusive) of second component
Returns
int-pair-sream
Definition at line 83 of file CCommon.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.cells().
Member Data Documentation
PACKAGEPATH
final String org.lightjason.trafficsimulation.CCommon.PACKAGEPATH = "org/lightjason/trafficsimulation/" static
Definition at line 48 of file CCommon.java.
Referenced by org.lightjason.trafficsimulation.ui.CHTTPServer.CHTTPServer(), org.lightjason.trafficsimulation.IBaseTest.loadconfiguration(), org.lightjason.trafficsimulation.simulation.stationary.trafficlight.ELightColorPedestrian.path(), and org.lightjason.trafficsimulation.simulation.stationary.trafficlight.ELightColorVehicle.path().