LightJason - TrafficSimulation: org.lightjason.trafficsimulation.runtime.IExperiment Interface Reference
org.lightjason.trafficsimulation.runtime.IExperiment Interface Reference
a single experiment run
Public Member Functions
Stream< IAgent<?> > agents ()
returns a stream of the agents
boolean parallel ()
execute agents in parallel
int simulationsteps ()
maximum simulation steps
IStatistic statistic ()
returns tha simulation statistic
Detailed Description
Definition at line 34 of file IExperiment.java.
Member Function Documentation
agents()
Stream<IAgent<?> > org.lightjason.trafficsimulation.runtime.IExperiment.agents ()
Returns
agent stream
Referenced by org.lightjason.trafficsimulation.runtime.CRuntime.execute().
parallel()
boolean org.lightjason.trafficsimulation.runtime.IExperiment.parallel ()
Returns
boolean flag for parallel execution
Referenced by org.lightjason.trafficsimulation.runtime.CRuntime.execute().
simulationsteps()
int org.lightjason.trafficsimulation.runtime.IExperiment.simulationsteps ()
Returns
simulation steps
Referenced by org.lightjason.trafficsimulation.runtime.CRuntime.execute().
statistic()
IStatistic org.lightjason.trafficsimulation.runtime.IExperiment.statistic ()
Returns
statistic