LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.environment.IEnvironment Interface Reference
org.lightjason.trafficsimulation.simulation.environment.IEnvironment Interface Reference
environment interface
Public Member Functions
boolean empty (final DoubleMatrix1D p_position)
checks if a position is empty
IObject<?> get (final DoubleMatrix1D p_position)
returns an object from the given position
IMoveable<?> move (final IMoveable<?> p_object, final DoubleMatrix1D p_position)
sets an object to the position and changes the object position
IObject<?> remove (final IObject<?> p_object)
removes an element from a position
List< DoubleMatrix1D > route (final DoubleMatrix1D p_start, final DoubleMatrix1D p_end)
calculate route
double routestimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
calculate estimated time of a route
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.IObject< T extends IAgent<?>
Stream< ILiteral > literal (final IObject<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IObject<?>> p_object)
get literal of the object
String name ()
name of the object
DoubleMatrix1D position ()
position of the object
Detailed Description
Definition at line 37 of file IEnvironment.java.
Member Function Documentation
empty()
boolean org.lightjason.trafficsimulation.simulation.environment.IEnvironment.empty (final DoubleMatrix1D p_position)
Parameters
p_position position
Returns
boolean result
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
get()
IObject<?> org.lightjason.trafficsimulation.simulation.environment.IEnvironment.get (final DoubleMatrix1D p_position)
Parameters
p_position position vector
Returns
object or null
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
move()
IMoveable<?> org.lightjason.trafficsimulation.simulation.environment.IEnvironment.move (final IMoveable<?> p_object, final DoubleMatrix1D p_position)
Parameters
p_object object, which should be moved (must store the current position)
p_position new position
Returns
updated object or object which uses the cell
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
Referenced by org.lightjason.trafficsimulation.simulation.movable.TestCVehicle.testMoving().
remove()
IObject<?> org.lightjason.trafficsimulation.simulation.environment.IEnvironment.remove (final IObject<?> p_object)
Parameters
p_object element
Returns
element
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
route()
List<DoubleMatrix1D> org.lightjason.trafficsimulation.simulation.environment.IEnvironment.route (final DoubleMatrix1D p_start, final DoubleMatrix1D p_end)
Parameters
p_start start position
p_end target position
Returns
list of tuples of the cellindex
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.route().
routestimatedtime()
double org.lightjason.trafficsimulation.simulation.environment.IEnvironment.routestimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
Parameters
p_route current route
p_speed current speed
Returns
estimated time
Implemented in org.lightjason.trafficsimulation.simulation.environment.CEnvironment.
Referenced by org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >.routeestimatedtime().