LightJason - TrafficSimulation: org.lightjason.trafficsimulation.simulation.movable.CVehicle Class Reference
org.lightjason.trafficsimulation.simulation.movable.CVehicle Class Reference
vehicle class
Classes
class CGenerator
generator class
Protected Member Functions
final Stream< ILiteral > individualliteral (final Stream< IObject<?>> p_object)
Protected Member Functions inherited from org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >
IBaseMoveable (final IAgentConfiguration< T > p_configuration, final IEnvironment p_environment, final String p_functor, final String p_name, final DoubleMatrix1D p_position, final DoubleMatrix1D p_size)
ctor
Private Member Functions
CVehicle (final IAgentConfiguration< CVehicle > p_configuration, final IEnvironment p_environment, final String p_name, final DoubleMatrix1D p_position)
ctor
void accelerate (final Number p_value)
void deccelerate (final Number p_value)
Static Private Attributes
static final AtomicLong COUNTER = new AtomicLong()
generator counter
static final String FUNCTOR = "vehicle"
literal functor
static final long serialVersionUID = 1256507850032527860L
serial id
Additional Inherited Members
Public Member Functions inherited from org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >
void move (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
move
boolean moveable (final ObjectMatrix2D p_grid, final DoubleMatrix1D p_newposition)
moveable
Static Protected Attributes inherited from org.lightjason.trafficsimulation.simulation.movable.IBaseMoveable< CVehicle >
static final String GROUP
group ov all agents
Detailed Description
Definition at line 49 of file CVehicle.java.
Constructor & Destructor Documentation
CVehicle()
org.lightjason.trafficsimulation.simulation.movable.CVehicle.CVehicle (final IAgentConfiguration< CVehicle > p_configuration, final IEnvironment p_environment, final String p_name, final DoubleMatrix1D p_position) private
Parameters
p_configuration agent configuration
p_environment environment
p_position position
Definition at line 72 of file CVehicle.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.CVehicle.CGenerator.generate().
Member Function Documentation
accelerate()
void org.lightjason.trafficsimulation.simulation.movable.CVehicle.accelerate (final Number p_value) private
Definition at line 91 of file CVehicle.java.
deccelerate()
void org.lightjason.trafficsimulation.simulation.movable.CVehicle.deccelerate (final Number p_value) private
Definition at line 98 of file CVehicle.java.
individualliteral()
final Stream<ILiteral> org.lightjason.trafficsimulation.simulation.movable.CVehicle.individualliteral (final Stream< IObject<?>> p_object) protected
Definition at line 83 of file CVehicle.java.
Member Data Documentation
COUNTER
final AtomicLong org.lightjason.trafficsimulation.simulation.movable.CVehicle.COUNTER = new AtomicLong() static private
Definition at line 62 of file CVehicle.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.CVehicle.CGenerator.generate(), and org.lightjason.trafficsimulation.simulation.movable.CVehicle.CGenerator.resetcount().
FUNCTOR
final String org.lightjason.trafficsimulation.simulation.movable.CVehicle.FUNCTOR = "vehicle" static private
Definition at line 58 of file CVehicle.java.
Referenced by org.lightjason.trafficsimulation.simulation.movable.CVehicle.CGenerator.generate().
serialVersionUID
final long org.lightjason.trafficsimulation.simulation.movable.CVehicle.serialVersionUID = 1256507850032527860L static private
Definition at line 54 of file CVehicle.java.